name: todone
description: "  A simple and intuitive To-Do app designed to help you organize your daily tasks with ease.
  Add, edit, and complete tasks effortlessly while keeping your day structured and productive.
  Lightweight, clean, and built with Flutter for a smooth user experience."

publish_to: 'none'

version: 1.0.4+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
# Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
# Databases
  hive: ^2.2.3
# Directories Handler
  path_provider: ^2.1.3
# Dependency Injection
  get_it: ^8.3.0
# State Managment
  flutter_bloc: ^9.1.1
  # SVG
  flutter_svg: ^2.2.1
# Shard prefs
  shared_preferences: ^2.5.3
# Sound
  audioplayers: ^6.5.1
# pomodoro- lottie
  lottie: ^3.3.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # App Icon & Splash Screen Packages
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.7
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/svg/
    - assets/sound/
    - assets/lottie/
  # fonts:

# App Logo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/app_icon.png"

# App Splash Screen
flutter_native_splash:
  android: true
  ios: true
  image: assets/logo/splash_icon.png
  color: "#18384A"  
  # color: "#E8F5E9"  
  android_12:
    # color: "#FFFFFF"
    image: "assets/logo/splash_icon.png" 
    color: "#18384A"

